apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helloworld
  namespace: helloworld
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: helloworld
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
