apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: disallow-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - helloworld
      validate:
        message: "Image tag ':latest' is not allowed. Use a specific digest or tag."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
