apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-latest-tag.yaml
  - require-resource-limits.yaml
  - require-non-root.yaml
  - require-readonly-rootfs.yaml
  - disallow-privileged.yaml
  - verify-image-signature.yaml
