apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld-tls
  namespace: istio-ingress
spec:
  secretName: helloworld-tls
  dnsNames:
    - "*.lab.umarzaman.ca"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
