apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helloworld-secret
  namespace: helloworld
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: helloworld-secret
  data:
    - secretKey: value
      remoteRef:
        key: helloworld-secret
        property: value
