apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/helloworld
  - externalsecret.yaml
  - secretstore.yaml
  - virtualservice.yaml
  - gateway.yaml
  - certificate.yaml
  - clusterissuer.yaml
  - peerauthentication.yaml
  - authorizationpolicy.yaml
images:
  - name: us-central1-docker.pkg.dev/gke-infrastructure-493002/platform/helloworld
    newTag: b60462510df763e5b98575d2ce5dc09f2db7a6f3
