apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/helloworld
  - externalsecret.yaml
  - secretstore.yaml
  - virtualservice.yaml
  - gateway.yaml
  - certificate.yaml
  - clusterissuer.yaml
  - cloudflare-externalsecret.yaml
images:
  - name: REGION-docker.pkg.dev/PROJECT_ID/helloworld/helloworld
    newTag: latest
