apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: PROJECT_ID  # replace with GCP project ID
      auth:
        workloadIdentity:
          clusterLocation: REGION  # replace with GCP region
          clusterName: CLUSTER_NAME  # replace with GKE cluster name
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
