apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.3.7
    helm:
      values: |
        admissionController:
          serviceAccount:
            annotations:
              iam.gke.io/gcp-service-account: kyverno-ar@gke-infrastructure-493002.iam.gserviceaccount.com
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        backgroundController:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        cleanupController:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        reportsController:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        cleanupJobs:
          admissionReports:
            image:
              registry: registry.bitnami.com
          clusterAdmissionReports:
            image:
              registry: registry.bitnami.com
          ephemeralReports:
            image:
              registry: registry.bitnami.com
          clusterEphemeralReports:
            image:
              registry: registry.bitnami.com
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
